# code: language=yaml
# ansible-lint ./052-playbook_nagios_clients.yaml
# ansible-playbook -i ./inventory.yaml ./052-playbook_nagios_clients.yaml

#######################################################################
# Gather facts for all hosts to allow building Nagois NRPE ip
- hosts: all
  tasks:
    - name: Gather facts
      setup:

#######################################################################
- name: KVM Lab1 playbook for workers in nagios example 
  hosts: kmvlabhosts_workers

  vars:

  tasks:

    #######################################################################
    # Install 
    - name: Install nagios client 
      become: true
      ansible.builtin.package:
        name: nagios-nrpe-plugin, nagios-plugins, nagios-nrpe-server, monitoring-plugins-contrib
        state: present

    #######################################################################
    # Configure

    - name: Ensure nrpe allows requests from Nagios01
      become: true
      ansible.builtin.lineinfile:
        path: /etc/nagios/nrpe_local.cfg
        regexp: '^allowed hosts='
        line: "allowed_hosts={{ hostvars['lab-nagios01'].ansible_default_ipv4.address }}"

    - name: NRPE Nagios Check disk vda1
      become: true
      ansible.builtin.lineinfile:
        path: /etc/nagios/nrpe_local.cfg
        regexp: '^command[check_vda1]'
        line: "command[check_vda1]=/usr/lib/nagios/plugins/check_disk -w 20% -c 10% -p /dev/vda1"

    - name: NRPE Nagios Check SSH on ip
      become: true
      ansible.builtin.lineinfile:
        path: /etc/nagios/nrpe_local.cfg
        regexp: '^command[check_ssh]'
        line: "command[check_ssh]=/usr/lib/nagios/plugins/check_ssh {{ hostvars['lab-nagios01'].ansible_default_ipv4.address }}"

    - name: NRPE Nagios Check APT
      become: true
      ansible.builtin.lineinfile:
        path: /etc/nagios/nrpe_local.cfg
        regexp: '^command[check_apt]'
        line: "command[check_apt]=/usr/lib/nagios/plugins/check_apt"

    - name: NRPE Nagios Check CPU Usage
      become: true
      ansible.builtin.lineinfile:
        path: /etc/nagios/nrpe_local.cfg
        regexp: '^command[check_cpu]'
        line: "command[check_cpu]=/usr/lib/nagios/plugins/check_cpu_stats.sh -w 75% -c 90%"

    - name: NRPE Nagios Check Memory Free
      become: true
      ansible.builtin.lineinfile:
        path: /etc/nagios/nrpe_local.cfg
        regexp: '^command[check_memory]'
        line: "command[check_memory]=/usr/lib/nagios/plugins/check_memory --available --units MiB -w 70%: -c 10%"

    #TODO: 
    # open files
    # netstat
    # if nagios graphs

    # sudo systemctl restart nagios-nrpe-server.service
    - name: Restart nagios-nrpe-server
      become: yes
      service:
        name: nagios-nrpe-server
        state: restarted
